services:
  database:
    image: postgres:16-alpine
    container_name: url_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_service_api
    restart: always
    environment:
      - APP_ENV=NON_PROD
    volumes:
      - ./secrets:/secrets:ro
    ports:
      - "8080:8000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgdata: