apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sakibmondal7/url_shortner:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: mysql+pymysql://admin:secret@mysql-service:3306/url_shortner
        envFrom:
        - secretRef:
            name: db-secrets