apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  mysql-root-password: c2VjcmV0X3Jvb3Q=          # "secret_root"
  mysql-database: dXJsX3Nob3J0bmVy               # "url_shortner"
  mysql-user: YWRtaW4=                           # "admin"
  mysql-password: c2VjcmV0                       # "secret"